name: Film Botu Güncelleyici

on:
  schedule:
    # Her gün saat 00:00 ve 12:00'da çalışır (UTC saati)
    - cron: '0 0,12 * * *'
  workflow_dispatch: # Manuel çalıştırmak için buton ekler

permissions:
  contents: write

jobs:
  update-movies:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Çek (Checkout)
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Kütüphaneleri Yükle
      run: |
        pip install -r requirements.txt

    - name: Botu Çalıştır
      env:
        # Site adresi değişirse buradan veya Settings -> Secrets'tan değiştirebilirsin
        SITE_URL: ${{ secrets.SITE_URL || 'https://dizipal1225.com/filmler' }}
      run: python main.py

    - name: Değişiklikleri Kaydet (Commit & Push)
      run: |
        git config --global user.name "Film Botu"
        git config --global user.email "bot@github.com"
        git add movies.json index.html
        # Eğer değişiklik varsa commit at, yoksa hata verme
        git commit -m "Otomatik güncelleme: Yeni filmler eklendi" || echo "Değişiklik yok"
        git push
